import AboutUs from "@/partials/homepage/aboutus";
import Booking from "@/partials/homepage/booking";
import Rooms from "@/partials/homepage/rooms";
import Slider from "@/partials/homepage/slides";
import { Box, useMediaQuery } from "@mui/material";
import Head from "next/head";

export default function Home() {

  const matches = useMediaQuery('(max-width:720px)');

  return (
    <>
      <Head>
        <title>Karaoke Zone 9 - 179 Nguyễn Tuân</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box marginLeft={{xs: 0, md: '300px'}} mt={{xs: 8, md: 0}}>
        {!matches && <Slider />}
        <AboutUs />
        <Booking />
        <Rooms />
      </Box>
    </>
  );
}
